name: do_an_lap_trinh_android
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  firebase_auth: ^6.1.0
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  convex_bottom_bar: ^3.2.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  flutter_rating_bar: ^4.0.1
  firebase_analytics: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
